spring:
  profiles:
    active:
      -  EN
      -  cat
      -  prod
wiwiel:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlUrl

---
spring:
  config:
    activate:
      on-profile: prod
wiwiel:
  username: ProdYmlUserName
  password: ProdYmlPassword
  jdbcurl: ProdYmlUrl